name: E2E Regression suite


on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '* 3 * * *'
  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],test.*"

jobs:
  Chrome_Linux:
    runs-on: ubuntu_latest
    permissions: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name:  setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'


      - name: install mvn
        uses: stCarolas/setup-maven@v5
        with:
           maven-version: 3.9.11
      - name: Running Tests
        run : mvn test -Dtest="${TARGET}" -DexcutioanType="local" -DbrowserType="Chrome" clean test
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
            name: chrome_linux_report
            path: "Reports/*.html"

  Edge_windows_test:
    runs-on: windows_latest
    permissions: write
    steps:
      - name: checkout code
        uses: actions/checkout@v5
      - name:  setup java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'


      - name: install mvn
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.11
      - name: Running Tests
        run : mvn test -Dtest="${TARGET}" -DexcutioanType="local" -DbrowserType="Edge" clean test
      - name: upload test results
        uses: actions/upload-artifact@v4
        with:
          name: edge_linux_report
          path: "Reports/*.html"


